common-codegen/build.gradle
common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/model/codegen/BeanGenerator.java

Add @NotNull annotation for required fields

---

common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/model/codegen/ObjectTypeTransformer.java

Remove NotNull annotations from setter methods.

---

.gitignore
annotations/build.gradle
annotations/src/main/java/io/vrap/rmf/codegen/common/processor/annotations/ExtensionMethod.java
annotations/src/main/java/io/vrap/rmf/codegen/common/processor/annotations/ModelExtension.java
annotations/src/main/java/io/vrap/rmf/codegen/common/processor/extension/ExtensionMapper.java
annotations/src/main/java/io/vrap/rmf/codegen/common/processor/extension/ExtensionMapperFactory.java
annotations/src/main/java/io/vrap/rmf/codegen/common/processor/processor/ModelExtensionProcessor.java
annotations/src/test/java/AnnotationProcessorTests.java
build.gradle
codegen-gradle-plugin/build.gradle
codegen-gradle-plugin/src/main/java/io/vrap/rmf/codegen/plugin/RamlCodeGeneratorTask.java
common-codegen/build.gradle
common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/extensions/JavaSTFileSwitch.java
common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/extensions/RmfModelAdaptor.java
common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/extensions/STCodeGenerator.java
common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/extensions/types/AnyTypeExtension.java
common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/extensions/types/DescriptionFacetExtension.java
common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/extensions/types/ObjectTypeExtension.java
common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/extensions/types/PropertyExtension.java
common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/extensions/types/StringExtension.java
common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/extensions/types/StringTypeExtension.java
common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/injection/GeneratorComponent.java
common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/injection/GeneratorModule.java
common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/util/TypeNameSwitch.java
common-codegen/src/main/resources/strTemplate/objectType.stg
common-codegen/src/main/resources/strTemplate/stringType.stg
common-codegen/src/test/java/io.vrap.rmf.codegen.common/CodeGeneratorTest.java
common-codegen/src/test/java/io.vrap.rmf.codegen.common/CustomObjectAdapter.java
settings.gradle

Add code generation using string template

Adding type extensions

---

kt-code-generators/src/main/kotlin/io/vrap/codegen/kt/languages/java/plantuml/PlantUmlDiagramProducer.kt
kt-code-generators/src/main/kotlin/io/vrap/codegen/kt/languages/java/plantuml/PlantUmlModule.kt
kt-code-generators/src/main/kotlin/io/vrap/codegen/kt/languages/java/plantuml/PlantUmlRelations.kt
kt-code-generators/src/test/kotlin/io/vrap/codegen/kt/languages/TestCodeGenerator.kt

Plant uml diagram generator

---

common-codegen-kt/src/main/kotlin/io/vrap/rmf/codegen/kt/types/AnyTypeProvider.kt
common-codegen-kt/src/main/kotlin/io/vrap/rmf/codegen/kt/types/LanguageBaseTypes.kt
kt-code-generators/src/main/kotlin/io/vrap/codegen/kt/languages/java/JavaBaseTypes.kt

adding support for long type formats.

Add support for long type

---

kt-code-generators/src/main/kotlin/io/vrap/codegen/kt/languages/extensions/ObjectTypeExtensions.kt
kt-code-generators/src/main/kotlin/io/vrap/codegen/kt/languages/java/extensions/ObjectTypeExtensions.kt
kt-code-generators/src/main/kotlin/io/vrap/codegen/kt/languages/java/model/JavaObjectTypeRenderer.kt

Fix unused import of class itself

---

kt-code-generators/src/main/kotlin/io/vrap/codegen/kt/languages/java/client/SpringClientRenderer.kt
kt-code-generators/src/main/kotlin/io/vrap/codegen/kt/languages/java/extensions/JavaVrapExtensions.kt

Our client doesen't generate query params.
This PR aim to fix it.

Fix our spring client generator

---

common-codegen-kt/src/main/kotlin/io/vrap/rmf/codegen/kt/CodeGeneratorConfig.kt
common-codegen-kt/src/main/kotlin/io/vrap/rmf/codegen/kt/di/GeneratorModule.kt
common-codegen-kt/src/main/kotlin/io/vrap/rmf/codegen/kt/di/VrapConstants.kt
common-codegen-kt/src/main/kotlin/io/vrap/rmf/codegen/kt/types/PackageProvider.kt
kt-code-generators/src/main/kotlin/io/vrap/codegen/kt/languages/java/JavaSubTemplates.kt
kt-code-generators/src/main/kotlin/io/vrap/codegen/kt/languages/java/client/SpringClientRenderer.kt
kt-code-generators/src/main/kotlin/io/vrap/codegen/kt/languages/php/model/PhpCollectionRenderer.kt
kt-code-generators/src/main/kotlin/io/vrap/codegen/kt/languages/php/model/PhpFileProducer.kt
kt-code-generators/src/main/kotlin/io/vrap/codegen/kt/languages/php/model/PhpMethodRenderer.kt
kt-code-generators/src/main/kotlin/io/vrap/codegen/kt/languages/php/model/PhpObjectTypeRenderer.kt
kt-code-generators/src/test/kotlin/io/vrap/codegen/kt/languages/TestCodeGenerator.kt

now we can generate separate package for model and client

Separate package for client model

---

cli-application/build.gradle
cli-application/src/main/resources/plugin.properties
codegen-gradle-plugin/build.gradle
codegen-gradle-plugin/src/main/resources/plugin.properties

i used to copy some properties of the `plugin.properties` to make the generator work, but thanks to @jenschude i found out that we can copy all properties without picking specific ones.

Append plugin.properties files

---

codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/java/client/SpringClientRenderer.kt

#43_spring_retryable_fully_configurable 

---

api-spec/types/error.raml
cli-application/src/main/kotlin/io/vrap/rmf/codegen/cli/CodegeneratorApp.kt
codegen-gradle-plugin/src/main/kotlin/io/vrap/rmf/codegen/plugin/Generator.kt
codegen-gradle-plugin/src/main/kotlin/io/vrap/rmf/codegen/plugin/RamlCodeGeneratorTask.kt
codegen-gradle-plugin/src/test/kotlin/io.vrap.rmf.codegen.common/BuildLogicFunctionalTest.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/typescript/joi/JoiBaseTypes.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/typescript/joi/JoiModule.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/typescript/joi/JoiObjectTypeExtensions.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/typescript/joi/JoiValidatorModuleRenderer.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/typescript/model/EObjectTypeExtensions.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/typescript/model/TsObjectTypeExtensions.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/typescript/model/TypeScriptBaseTypes.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/typescript/model/TypeScriptModelModule.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/typescript/model/TypeScriptModuleRenderer.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/typescript/model/TypeScriptVrapExtensions.kt
codegen-renderers/src/test/kotlin/io/vrap/codegen/languages/TestCodeGenerator.kt

Now we can generate a joi validator also
this includes support for:
- polymorphic types.
- pattern properties.

Generating joi validator

---

codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/java/client/SpringClientRenderer.kt

Spring client misshandles endpoints with no return, 200 for success, 4XX otherwise, this PR should fix that

Fix spring client

---

cli-application/build.gradle
codegen-core/build.gradle
codegen-gradle-plugin/build.gradle
codegen-gradle-plugin/src/main/kotlin/io/vrap/rmf/codegen/plugin/Generator.kt
codegen-gradle-plugin/src/main/kotlin/io/vrap/rmf/codegen/plugin/RamlCodeGeneratorTask.kt
codegen-gradle-plugin/src/test/kotlin/io.vrap.rmf.codegen.common/BuildLogicFunctionalTest.kt
codegen-renderers/build.gradle
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/java/groovy/dsl/GroovyDslRenderer.kt

This pr allow the gradle plugin to generate the groovy dsl

Add groovy dsl generation to gradle plugin

---

codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/typescript/joi/JoiValidatorModuleRenderer.kt

Add handling of additional properties to JOI generator.

---

codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/extensions/ObjectTypeExtensions.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/java/extensions/JavaObjectTypeExtensions.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/java/extensions/JavaStringTypeExentsions.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/java/model/JavaObjectTypeRenderer.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/java/model/JavaStringTypeRenderer.kt

Add logic to make discriminator value immutable.

---

api-spec/types/error.raml
api-spec/types/price-mapping.raml
api-spec/types/unresolved-import-resource.raml
build.gradle

This update the RMF version to the latest one that includes fixes for the validation.
That's why i had to fix the api spec too 😉

Update rmf version

---

codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/java/commands/JavaCommandsRenderer.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/java/file/producers/JavaModelClassFileProducer.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/java/file/producers/JavaModelDraftBuilderFileProducer.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/java/file/producers/JavaStaticFilesProducer.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/java/modules/JavaCompleteModule.kt

Generation of builders for draft model classes.

Generate draft builder

---

codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/java/commands/JavaCommandsRenderer.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/java/file/producers/JavaModelClassFileProducer.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/java/modules/JavaCompleteModule.kt

Barebone commands functionality. PR contains just one minor bug fix as the rest of the command generation was merged with the previous PR.

fixed command path arguments bug

---

codegen-core/src/main/kotlin/io/vrap/rmf/codegen/types/PackageProvider.kt

Remove resource sub package.

---

codegen-gradle-plugin/src/main/kotlin/io/vrap/rmf/codegen/plugin/Generator.kt
codegen-gradle-plugin/src/main/kotlin/io/vrap/rmf/codegen/plugin/RamlCodeGeneratorTask.kt
codegen-gradle-plugin/src/test/kotlin/io.vrap.rmf.codegen.common/BuildLogicFunctionalTest.kt

Add customTypeMapping support to our gradle plugin.

---

cli-application/build.gradle
codegen-core/build.gradle
codegen-core/src/main/kotlin/io/vrap/rmf/codegen/di/GeneratorModule.kt
codegen-core/src/main/kotlin/io/vrap/rmf/codegen/di/VrapConstants.kt
codegen-core/src/main/kotlin/io/vrap/rmf/codegen/types/PackageProvider.kt
codegen-gradle-plugin/build.gradle
codegen-renderers/build.gradle
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/php/model/PhpCollectionRenderer.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/php/model/PhpFileProducer.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/php/model/PhpInterfaceObjectTypeRenderer.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/php/model/PhpMethodRenderer.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/php/model/PhpObjectTypeRenderer.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/typescript/client/files_producers/ApiRootFileProducer.kt

Since the named annotation is a bit confusing, i replaced it with a [BindingAnnotation](https://github.com/google/guice/wiki/BindingAnnotations)

Remove unsafe strings

---

codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/typescript/client/files_producers/ClientFileProducer.kt
codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/typescript/client/files_producers/ConstEntities.kt
codegen-renderers/src/test/resources/typescript/tsconfig.json

Modifications in order to make the tscode "strict"

Make typescript code strict

---

gradle/wrapper/gradle-wrapper.properties
tools/codegen-gradle-plugin/README.md

Since our work is taking shape it's high time we start documenting i
This PR tries to add the gradle plugin doc

Add gradle plugin doc

---

languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/joi/JoiValidatorModuleRenderer.kt

Fix bug in joi rendering of an object type with a discriminator.

---

languages/javalang/java-renderer/src/main/kotlin/io/vrap/codegen/languages/javalang/client/SpringClientRenderer.kt
languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/model/TypeScriptObjectTypeExtensions.kt

When the path contains an enum the request doesn't work correctly anymore, this pr fixes this use case

Support enum in a path param

---

languages/javalang/java-renderer/src/main/kotlin/io/vrap/codegen/languages/javalang/client/SpringClientRenderer.kt

Refactor code to use super type TypedElement.
Fix issue when query parameter is an enum.
Closes #113

Fix issue when query parameter is an enum

---

codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/extensions/DescriptionFacetExtensions.kt
languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/TsExtensions.kt
languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/client/RequestBuilder.kt
languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/client/files_producers/ApiRootFileProducer.kt
languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/model/TypeScriptModuleRenderer.kt

Since typescriptLang accepts markdown as doc, i changes the code generator to support it.

Add documentation

---

README.md
codegen-core/build.gradle
codegen-core/src/main/kotlin/io/vrap/rmf/codegen/di/GeneratorModule.kt
codegen-renderers/build.gradle
languages/javalang/builder-renderer/java-builder-client/build.gradle
languages/javalang/java-base/build.gradle
languages/javalang/java-renderer/build.gradle
languages/php/build.gradle
languages/postman/build.gradle
languages/ramldoc/build.gradle
languages/typescript/build.gradle
scripts/install.sh
tools/cli-application/build.gradle
tools/cli-application/src/main/kotlin/io/vrap/rmf/codegen/cli/CodegeneratorApp.kt
tools/codegen-gradle-plugin/build.gradle

Add version option to cli

---

tools/cli-application/src/main/kotlin/io/vrap/rmf/codegen/cli/CodegeneratorApp.kt
tools/cli-application/src/main/kotlin/io/vrap/rmf/codegen/cli/GenerateSubcommand.kt
tools/cli-application/src/main/kotlin/io/vrap/rmf/codegen/cli/Utils.kt
tools/cli-application/src/main/kotlin/io/vrap/rmf/codegen/cli/VerifySubcommand.kt

Since the watch option is so useful i decided to add it to the verify command.

Add watch option to Verify command

---

README.md
tools/cli-application/src/main/kotlin/io/vrap/rmf/codegen/cli/CodegeneratorApp.kt
tools/cli-application/src/main/kotlin/io/vrap/rmf/codegen/cli/GenerateSubcommand.kt
tools/cli-application/src/main/kotlin/io/vrap/rmf/codegen/cli/Utils.kt
tools/cli-application/src/main/kotlin/io/vrap/rmf/codegen/cli/VerifySubcommand.kt

Added some colors for a more compelling CLI

Add some life to the cli

---

languages/javalang/builder-renderer/java-builder-client/src/main/kotlin/io/vrap/codegen/languages/javalang/client/builder/requests/JavaHttpRequestRenderer.kt
languages/javalang/java-base/src/main/kotlin/io/vrap/codegen/languages/java/base/extensions/JavaEObjectTypeExtensions.kt
languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/client/files_producers/ClientConstants.kt

Previously the image upload wasn't working properly (it was more or less a placeholder), this pr tries to fix this by handling this ignored use case.

Update code generator to support file update.

---

languages/ramldoc/src/main/kotlin/io/vrap/codegen/languages/ramldoc/extensions/VrapExtensions.kt
languages/ramldoc/src/main/kotlin/io/vrap/codegen/languages/ramldoc/model/ApiRamlRenderer.kt
languages/ramldoc/src/main/kotlin/io/vrap/codegen/languages/ramldoc/model/RamlResourceRenderer.kt

add curl code example to RAMLdoc

---

build.gradle

Update to latest RMF version which provides better error messages.

Update to latest RMF version which provides better error messages.

---

codegen-core/src/main/kotlin/io/vrap/rmf/codegen/di/ApiProvider.kt
tools/cli-application/src/main/kotlin/io/vrap/rmf/codegen/cli/VerifySubcommand.kt

Improve error logging to make it easier to read.

Improve error logging

---

codegen-core/build.gradle
codegen-core/src/main/kotlin/io/vrap/rmf/codegen/rendring/CoreCodeGenerator.kt
tools/cli-application/build.gradle

Since now we generate a lot files, a suggestion here to squeeze a bit of performance via parallel file writing.

Add parallel generation.

---

languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/joi/JoiValidatorModuleRenderer.kt

This PR to improve alternatives with attached `.when`

ts joi chian alternatives with .when to improve errors

---

languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/joi/JoiValidatorModuleRenderer.kt
languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/server/ServerRenderer.kt

Upgrade generated Joi Schema below are some points:
- use `valid` instead of `only`
- use `link` instead of `lazy`

upgrade joi 17.03

---

languages/ramldoc/src/main/kotlin/io/vrap/codegen/languages/ramldoc/model/ApiRamlRenderer.kt

render annotations on API and SecurityScheme level

more dynamic renderer for SecuritySchemes

---

languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/model/TypeScriptVrapExtensions.kt
languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/test/TypescriptRequestTestRenderer.kt
languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/test/TypescriptTestModule.kt
languages/typescript/src/test/kotlin/io/vrap/codegen/languages/TestCodeGenerator.kt
tools/cli-application/src/main/kotlin/io/vrap/rmf/codegen/cli/GenerateSubcommand.kt

Adding TypeScript Testing Module to generate unit tests for request builders

Adding TypeScript Testing Module

---

languages/csharp/src/main/kotlin/io/vrap/codegen/languages/csharp/extensions/CsharpMethodExtensions.kt
languages/csharp/src/main/kotlin/io/vrap/codegen/languages/csharp/extensions/CsharpObjectTypeExtensions.kt
languages/csharp/src/main/kotlin/io/vrap/codegen/languages/csharp/extensions/CsharpVrapExtensions.kt
languages/csharp/src/main/kotlin/io/vrap/codegen/languages/csharp/extensions/ResourceImplExtensions.kt
languages/csharp/src/main/kotlin/io/vrap/codegen/languages/csharp/model/CsharpModelInterfaceRenderer.kt
languages/csharp/src/main/kotlin/io/vrap/codegen/languages/csharp/model/CsharpObjectTypeRenderer.kt
languages/csharp/src/main/kotlin/io/vrap/codegen/languages/csharp/requests/CsharpHttpRequestRenderer.kt
languages/csharp/src/main/kotlin/io/vrap/codegen/languages/csharp/requests/CsharpRequestBuilderResourceRenderer.kt
languages/csharp/src/test/kotlin/io.vrap.codegen.languages.csharp/TestCodeGenerator.kt

- Adding "Impl" as Suffix for the classes and using interfaces in properties instead of classes 
- using DefaultTypeDiscriminator Attribute

Adjusting Csharp Code generator to handle History SDK

---

languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/server/ParameterGenerator.kt

Fix importing of the array types in parameter Generator like ProcessingState

Fix importing of the array types

---

ctp-validators/src/main/resources/ruleset.xml

Opened PR in the doc repo: https://github.com/commercetools/commercetools-docs/pull/1610

removed exclude from UpdateActionNameRule

---

ctp-validators/src/main/README.md

This PR adds a guide on how to add ctp validators

docs(ctp-validators): create guide on updating ctp validators

---

languages/go/src/main/kotlin/io/vrap/codegen/languages/go/client/ClientFileProducer.kt

This also sets the user-agent correctly on the OAuth2 requests

Go: Improve logic to set the user-agent on the http client

---

languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/client/files_producers/ClientFileProducer.kt

Remove querystring reference

---

languages/python/src/main/kotlin/io/vrap/codegen/languages/python/client/RequestBuilder.kt
languages/python/src/main/kotlin/io/vrap/codegen/languages/python/model/PythonModelRenderer.kt
languages/python/src/main/kotlin/io/vrap/codegen/languages/python/model/PythonSchemaRenderer.kt

This PR adds two minor changes to how the Python code is generated to fix a syntax error in the generated code.
See https://github.com/labd/commercetools-python-sdk/issues/141

Fix Python code generation

---

languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/client/TypescriptClientModule.kt
languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/client/files_producers/IndexFileProducer.kt

Export TypeScript Resource Members
[#464](https://github.com/commercetools/commercetools-sdk-typescript/issues/464)

Export TS Resource Members
