commercetools/rmf-codegen

- common-codegen/build.gradle
- common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/core/CodeGenerator.java
- common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/core/ConfigDecorator.java
- common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/core/ConfigDecoratorBase.java
- common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/model/codegen/BaseClass.java
- common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/model/codegen/BeanGenerator.java
- common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/model/codegen/ObjectTypeTransformer.java
- common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/model/codegen/StringTypeTransformer.java
- common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/model/codegen/TypeTransformer.java
- common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/util/CodeGeneratorUtil.java
- common-codegen/src/main/java/io/vrap/rmf/codegen/common/generator/util/TypeNameSwitch.java
Closes #5 
Now the code generator is separated into smaller blocks, This is just a first step, once the code is mature enough it would be separated into interfaces that contain the logic and that may work for multiple generators.
> Bean generator refactoring

- api-spec/annotationTypes/generator.raml
- api-spec/types/common.raml
- codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/java/extensions/DescriptionExtensions.kt
- codegen-renderers/src/main/kotlin/io/vrap/codegen/languages/java/model/JavaStringTypeRenderer.kt
This add support for rendering of `doc` annotations on enum values to our java model renderer.
> Add support for rendering of "doc"

- RELEASING.md
- build.gradle
- codegen-core/build.gradle
- codegen-renderers/build.gradle
- languages/javalang/builder-renderer/commercetools-java-base/build.gradle
- languages/javalang/builder-renderer/commercetools-java-client/build.gradle
- languages/javalang/builder-renderer/generated-code/build.gradle
- languages/javalang/builder-renderer/java-builder-client/build.gradle
- languages/javalang/java-base/build.gradle
- languages/javalang/java-renderer/build.gradle
- languages/php/build.gradle
- languages/typescript/build.gradle
- tools/cli-application/build.gradle
- tools/codegen-gradle-plugin/README.md
- tools/codegen-gradle-plugin/build.gradle
**Summary**
This PR enables us to publish our artifacts - including our gradle plugin - to bintray. This then allows us to remove this rather lrage artifact (90 MB) from our projects github repository.
And it still makes sense to publish our plugin to the gradle center, but to me it seems to be easier for now to publish our artifacts to bintray.
> Add publish to bintray

- tools/cli-application/build.gradle
This publishes our `cli-application` as a fat/shadowJar to bintray. The file name will follow the scheme ` cli-application-1.0.0-20200220154205-all.jar`.
> Add bintray publish of our cli-application shadowJar to our build.

- README.md
- build.gradle
- tools/cli-application/build.gradle
Looks like this was much easier then expected with the gradle plugin from palantir 😄 
It only took 30 minutes of my spare time 😎 
I only tested it locally on my MacBook, let's see if it works under linux too.
> Use nativeImage to build native executable for cli-application

- languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/server/ServerRenderer.kt
This PR adds the OAuth2 scopes defined for a RAML method to our generated hapi server. this then allows us to use a hapi authentication scheme that talks to our OAuth2 introspection api to retrieve the scopes of a given OAUth2 token (see also my prototype for such an authentication scheme: https://github.com/katmatt/hapi-oauth2-introspection).
> Add oauth2 scopes to generated hapi server

- languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/client/files_producers/ClientFileProducer.kt
- languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/server/ServerHelpers.kt
We want to use the `patch` method inside our `import-storage-service` and are currently blocked by the generator. I took a quick look and found this. Please let me know if I missed something that we should add to make it work.
> add patch MethodType

- languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/server/ServerRenderer.kt
- tools/codegen-gradle-plugin/src/main/kotlin/io/vrap/rmf/codegen/plugin/RamlCodeGeneratorTask.kt
Just a few fixes were necessary to fix it 😄 And we could still use our existing `tscpaths` solution 😎
> Fix codegen for import api

- languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/server/ServerRenderer.kt
This PR fixes the location of the auth config in our hapi server generator. A fixed gradle plugin version is available as `1.0.0-20200529111014`.
> Fix location of auth block.

- languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/joi/JoiValidatorModuleRenderer.kt
This PR fixes the bug in our generated joi validators for regex patterns. I left a todo because of an inconsistency in our api spec and I will follow up on it as soon as @danrleyt  finishes his current task.
The fix is released as version '1.0.0-20200603102711'' and you can try it locally.
> Fix joi validation regexp

- build.gradle
I found a bug in RMF, but couldn't reproduce it with `rmf-codegen` because it's using an old version of RMF. Hope this doesn't break anything, but the last published RMF version behaves differently than the version we used here!
> Update RMF version to be able to reproduce bug.

- languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/joi/JoiValidatorModuleRenderer.kt
This PR adds support for the `maxItems` facet to our generated joi validator.
> Add support for maxItems property to joi generator.

- languages/csharp/src/main/kotlin/io/vrap/codegen/languages/csharp/extensions/CsharpObjectTypeExtensions.kt
- languages/csharp/src/main/kotlin/io/vrap/codegen/languages/csharp/model/CsharpModelInterfaceRenderer.kt
Skip BaseResource Props from being presented in inherited in CSharp SDK
> Csharp - Skip BaseResource Props

- languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/server/ServerRenderer.kt
with this option set to false, then we have chance to collect all the validation errors instead of before aborting validation errors with the first error.
> ts: add abortEarly joi validation

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .gitignore
- README.md
- build.gradle
- tools/cli-application/build.gradle
When using RMF-Codegen in documenation we found it's minimal documentation and not only slightly hidden release artifact on Bintray hinders adoption and proper usage. 
Here's how the releases would look like: https://github.com/nkuehn/rmf-codegen/releases 
This 
* Overhauls the README and adds the CLI help output to the README so you can see all the glory without having to download it
* Adds an additional release CI workflow that builds a JAR and Mac / Linux native binaries and publishes these as a GitHub release, which has the advantage to have a browseable UI
General hints:
* windows binaries not built, there's some problem with the build which (I think) should only be tackled after the native builds are error free on the other platforms. 
* the linked javascript / NPM package is no …
> Release to GitHub, Native binaries on CI, README overhaul

- languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/server/ServerRenderer.kt
In Hapi v20, This PR updates the code generator to change Joi params now have to be `Joi.object()`
> update hapi params to use joi objects

- languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/joi/JoiValidatorModuleRenderer.kt
We are currently using joi's [object.unknown](https://joi.dev/api/?v=17.4.0#objectunknownallow) method call with the default setting. This means that we're ignoring unknown keys and don't pass them on to the handler. We would like to make this stricter, and throw when an unknown field is being passed. So this PR passed `false` into the method call to enable throwing.
Resolves #220
References https://github.com/commercetools/commercetools-importer/issues/1762
> pass false to joi object unknown method

- languages/python/src/main/kotlin/io/vrap/codegen/languages/python/model/InitFileProducer.kt
- languages/python/src/main/kotlin/io/vrap/codegen/languages/python/model/PythonModelRenderer.kt
- tools/cli-application/src/main/kotlin/io/vrap/rmf/codegen/cli/GenerateSubcommand.kt
This fixes three issues:
- The `.raml` check on the fileLocation failed on my laptop 
- The platform raml spec introduced a StringType which was not an enum, now handled correctly.
- Use `.last()` for getting the last part of a module name instead of the hardcoded the [1]
> Minor fixes to update the Python generator to work again

- languages/python/src/main/kotlin/io/vrap/codegen/languages/python/model/PythonModelRenderer.kt
- languages/python/src/main/kotlin/io/vrap/codegen/languages/python/model/PythonSchemaRenderer.kt
Don't render the names as `//` but instead use the `**kwargs` syntax
> Python: Fix handling of pattern properties

- languages/php/src/main/kotlin/io/vrap/codegen/languages/php/model/PhpMethodRenderer.kt
As the execute method is not returning the generic Template value, psalm is complaining about undefined methods when you use a returnType. With this the generic is also returned
> Add missing generic return to execute function

- languages/go/src/main/kotlin/io/vrap/codegen/languages/go/client/ClientFileProducer.kt
- languages/go/src/main/kotlin/io/vrap/codegen/languages/go/client/MethodRenderer.kt
If the HTTP status code returned by the server is not defined in the RAML
specs we would previously return an error indicating this. Instead we
now return a `GenericRequestError` with the status code, body and
response object.
> Go: Return `GenericRequestError` for unhandled http status codes

- languages/go/src/main/kotlin/io/vrap/codegen/languages/go/GoObjectTypeExtensions.kt
- languages/go/src/main/kotlin/io/vrap/codegen/languages/go/GoStringExtension.kt
- languages/go/src/main/kotlin/io/vrap/codegen/languages/go/client/ClientFileProducer.kt
- languages/go/src/main/kotlin/io/vrap/codegen/languages/go/client/RequestBuilder.kt
- languages/go/src/main/kotlin/io/vrap/codegen/languages/go/model/GoFileProducer.kt
The pattern properties are added to the struct. If only one pattern is
in the struct (most often the case) the name `ExtraValues` is used.
Otherwise the index is appended (e.g. `ExtraValues2`)
> Go: Implement support for pattern properties

- languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/client/files_producers/ClientFileProducer.kt
Use native `URLSearchParams` in place of deprecated `querystring` third-party package.
[#452](https://github.com/commercetools/commercetools-sdk-typescript/issues/452)
> Use native URLSearchParams

- languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/client/files_producers/ClientFileProducer.kt
The path params inside of the URI are not escaped. This leads to URLs that are not valid.
Example: A customer of ours is using special characters in its product key: `123455[P]`
The URL to update or retrieve the product by key is constructed then like `https://api.europe-west1.gcp.commercetools.com/konrad-dev-002/products/key=518210[P]'`
After the introduction of the change, the constructed url will look like this: `https://api.europe-west1.gcp.commercetools.com/konrad-dev-002/products/key=1234%5BP%5D`
> BMU-779: encode path params in typescript sdk for proper escaped URI

- README.md
- ctp-validators/src/main/README.md
- ctp-validators/src/main/kotlin/com/commercetools/rmf/validators/BooleanPropertyNameRule.kt
- ctp-validators/src/main/resources/ruleset.xml
- ctp-validators/src/test/groovy/com/commercetools/rmf/validators/ValidatorRulesTest.groovy
- ctp-validators/src/test/resources/boolean-property-name-rule.raml
- add rule: boolean properties must not have "is" as a prefix
- add the "validate" command in the README
> Rule: Boolean property name

- languages/go/src/main/kotlin/io/vrap/codegen/languages/go/client/MethodRenderer.kt
We currently overwrite values being set in GET queries. This changes the generator to use Add instead, which will append values
> fix: switched from values.Set to values.Add 

- languages/python/src/main/kotlin/io/vrap/codegen/languages/python/client/ApiRootFileProducer.kt
We don’t need to pass `self` to super(), this resulted in passing the invalid value twice
> fix(python): use correct base client init

- languages/bruno/src/main/kotlin/io/vrap/codegen/languages/bruno/model/BrunoModuleRenderer.kt
To match postman and co https://github.com/commercetools/rmf-codegen/blob/d81e2b25aae0df7a44001968fc2d25f195220fad/languages/postman/src/main/kotlin/io/vrap/codegen/languages/postman/model/PostmanModuleRenderer.kt#L41
> Bruno: Authentication URL doesn't embed path anymore

- languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/client/files_producers/ClientFileProducer.kt
Add missing field for ClientResponse interface
[721](https://github.com/commercetools/commercetools-sdk-typescript/pull/721) failing tests
> [Chore] Add Missing `originalRequest` Field to ClientResponse Interface

- languages/php/src/main/kotlin/io/vrap/codegen/languages/php/base/PhpBaseFileProducer.kt
adding a docblock in the ClientCredential class class https://commercetools.atlassian.net/jira/software/c/projects/DEVX/boards/386?selectedIssue=DEVX-404
> DEVX-404 adding a docblock in the clientcredential 
